version: "3.7"
services:
    zoo1:
        build: .
        image: kafka-example
        hostname: zoo1
        ports:
            - "2181:2181"
            - "9091:9091"
            - "9092:9092"
        expose: 
            - "2181"
            - "9091"
            - "9092"
        volumes:
            - ./resources/security-test2/sasl/zoo1/myid:/tmp/zookeeper/myid
            - ./resources/security-test2/sasl/zoo1/zookeeper.properties:/opt/kafka_2.12-2.4.0/config/zookeeper.properties
            - ./resources/security-test2/sasl/zoo1/zookeeper_jaas.conf:/opt/kafka_2.12-2.4.0/config/zookeeper_jaas.conf
        command:
            - /bin/sh
            - -c
            - |
                export KAFKA_OPTS=-Djava.security.auth.login.config=/opt/kafka_2.12-2.4.0/config/zookeeper_jaas.conf
                ./kafka_2.12-2.4.0/bin/zookeeper-server-start.sh ./kafka_2.12-2.4.0/config/zookeeper.properties
    zoo2:
        build: .
        image: kafka-example
        hostname: zoo2
        ports:
            - "22181:2181"
        expose: 
            - "22181"
        volumes:
            - ./resources/security-test2/sasl/zoo2/myid:/tmp/zookeeper/myid
            - ./resources/security-test2/sasl/zoo2/zookeeper.properties:/opt/kafka_2.12-2.4.0/config/zookeeper.properties
            - ./resources/security-test2/sasl/zoo2/zookeeper_jaas.conf:/opt/kafka_2.12-2.4.0/config/zookeeper_jaas.conf
        command:
            - /bin/sh
            - -c
            - |
                export KAFKA_OPTS=-Djava.security.auth.login.config=/opt/kafka_2.12-2.4.0/config/zookeeper_jaas.conf
                ./kafka_2.12-2.4.0/bin/zookeeper-server-start.sh ./kafka_2.12-2.4.0/config/zookeeper.properties
    zoo3:
        build: .
        image: kafka-example
        hostname: zoo3
        ports:
            - "32181:2181"
        expose: 
            - "32181"
        volumes:
            - ./resources/security-test2/sasl/zoo3/myid:/tmp/zookeeper/myid
            - ./resources/security-test2/sasl/zoo3/zookeeper.properties:/opt/kafka_2.12-2.4.0/config/zookeeper.properties
            - ./resources/security-test2/sasl/zoo3/zookeeper_jaas.conf:/opt/kafka_2.12-2.4.0/config/zookeeper_jaas.conf
        command:
            - /bin/sh
            - -c
            - |
                export KAFKA_OPTS=-Djava.security.auth.login.config=/opt/kafka_2.12-2.4.0/config/zookeeper_jaas.conf
                ./kafka_2.12-2.4.0/bin/zookeeper-server-start.sh ./kafka_2.12-2.4.0/config/zookeeper.properties
#     zoo3:
#         build: .
#         image: kafka-example
#         hostname: security-test-sasl
#         ports:
#             - "19091:19091"
#             - "9091:9091"
#         expose:
#             - "9091"
#             - "19091"
#         volumes:
#             - ./resources/security-test2/sasl/server-1.properties:/opt/kafka_2.12-2.4.0/config/server-1.properties
#             - ./resources/security-test2/sasl/server-2.properties:/opt/kafka_2.12-2.4.0/config/server-2.properties
#             - ./resources/security-test2/sasl/kafka_server_jaas.conf:/opt/kafka_2.12-2.4.0/config/kafka_server_jaas.conf
#             - ./resources/security-test2/sasl/zookeeper.properties:/opt/kafka_2.12-2.4.0/config/zookeeper.properties
#             - ./resources/security-test2/sasl/zookeeper_jaas.conf:/opt/kafka_2.12-2.4.0/config/zookeeper_jaas.conf
#             - ./resources/security-test2/keycerts:/opt/keycerts
#         command:
#             - /bin/sh
#             - -c
#             - |
#                 export KAFKA_OPTS=-Djava.security.auth.login.config=/opt/kafka_2.12-2.4.0/config/zookeeper_jaas.conf
#                 ./kafka_2.12-2.4.0/bin/zookeeper-server-start.sh ./kafka_2.12-2.4.0/config/zookeeper.properties
# 